#!/bin/bash

#344 Program 4 compile
#my dyslexia messed up the file names. corrected in objects.
gcc opt_enc.c -o otp_enc
gcc opt_enc_d.c -o otp_enc_d
gcc opt_dec.c -o otp_dec
gcc opt_dec_d.c -o otp_dec_d
gcc keygen.c -o keygen
